### ISSUE TITLE
Panel number doesn't match

### ISSUE THREAD

**Issue by LauraMcCluskey7** [AWGL/trio-panels#3]
Python query_panelapp.py 1 gives the panel for Neurofibromatosis instead of Thoracic aortic aneurysm or dissection

**Comment by erikwaskiewicz** [comment]
Reply from GEL service desk:

> Hi Erik Waskiewicz,
>
> Looking at the links that you've posted above, it appears that the way you are using the API is incorrect. For the version 1 of the API, the intended parameter for the query is the panel_id (previously referred to as hash_id), not the ID, e.g. https://panelapp.genomicsengland.co.uk/api/v1/panels/5596735822c1fc4f7d26e96d/ and https://panelapp.genomicsengland.co.uk/WebServices/get_panel/5596735822c1fc4f7d26e96d/. This is the panel identifier which is provided in the interpretation request, and this is a stable identifier across both versions.
> This endpoint shows the panels currently available, and the panel_id for each https://panelapp.genomicsengland.co.uk/WebServices/list_panels/
Examples on how to use the endpoint and some examples are available at https://panelapp.genomicsengland.co.uk/media/files/PanelApp_Webservices_Nov2017.txt 
>
> Please let us know if there is any other help we can provide,
> 
> Matt
